language: ruby
rvm:
  - 2.1.5
before_script:
  - cp config/application.travis.yml config/application.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database nilgiri_test;' -U postgres
  - bundle exec rake db:test:prepare
script: bundle exec rake spec
