Machine.create(name: 'beatmania IIDX 21 SPADA (SP)', difficulties: %w(NORMAL HYPER ANOTHER))
Machine.create(name: 'beatmania IIDX 21 SPADA (DP)', difficulties: %w(NORMAL HYPER ANOTHER))
Machine.create(name: "pop'n music Sunny Park", difficulties: %w(NORMAL HYPER EX))
Machine.create(name: 'GITADORA GuitarFreaks (GUITAR)', difficulties: %w(BASIC ADVANCED EXTREME MASTER))
Machine.create(name: 'GITADORA GuitarFreaks (BASS)', difficulties: %w(BASIC ADVANCED EXTREME MASTER))
Machine.create(name: 'GITADORA DrumMania', difficulties: %w(BASIC ADVANCED EXTREME MASTER))
Machine.create(name: 'DanceDanceRevolution (SP)', difficulties: %w(BEGINNER BASIC DIFFICULT EXPERT CHALLENGE))
Machine.create(name: 'DanceDanceRevolution (DP)', difficulties: %w(BASIC DIFFICULT EXPERT CHALLENGE))
Machine.create(name: 'jubeat saucer', difficulties: %w(BASIC ADVANCED EXTREME))
Machine.create(name: 'REFLEC BEAT colette', difficulties: %w(BASIC MEDIUM HARD))
Machine.create(name: 'SOUND VOLTEX II -infinite infection-', difficulties: %w(NOVICE ADVANCED EXHAUST INFINITE))
Machine.create(name: 'DanceEvolution ARCADE', difficulties: %w(LIGHT STANDARD EXTREME MASTER STEALTH))
Machine.create(name: 'ミライダガッキ', difficulties: %w(ベーシック スーパー ウルトラ))
Machine.create(name: 'maimai GreeN', difficulties: %w(EASY BASIC ADVANCED EXPERT MASTER))
